version: '3.1'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: lingo
      POSTGRES_PASSWORD: lingo
      POSTGRES_DB: lingoconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./audio:/usr/src/app/audio
    deploy:
      resources:
        limits:
          memory: 2g  # 메모리 제한을 4GB로 설정
        reservations:
          memory: 1g  # 예약 메모리를 2GB로 설정

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
