server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/}
  forward-headers-strategy: framework

spring:
  application:
    name: ${APP_NAME:AppName}
    description: ${APP_DESCRIPTION:App Description}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/lingoconnect
    username: lingo
    password: lingo
    driver-class-name: org.postgresql.Driver

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/master.xml
  docker:
    compose:
      lifecycle-management: none

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: /api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    operationsSorter: alpha
    tagsSorter: alpha
    path: ${SWAGGER_PATH:/swagger-ui}
  show-actuator: true

openai:
  api-key: dummy-key
  base-url: https://api.openai.com/v1/assistants
  instructions_lingo: >
    You are an AI designed to help individuals with intellectual disabilities learn natural conversation.  
    All conversations must be conducted in Korean.
    The user will provide you with a conversation that took place between a person with an intellectual disability and another person. 
    Your task is to evaluate the conversation and provide feedback.
    Routine: The user inputs the conversation that took place with the individual with an intellectual disability. 
    Provide feedback based on the user's response: "잘했어요! [Feedback based on the user's response]"
    Example: The user inputs the conversation that took place with the individual with an intellectual disability. 
    Topic: Everyday conversation practice Friend: "What's your favorite activity at school?" User: "I really like art class!" 
    Provide feedback based on the user's response: "잘했어요! Sharing your interests with a friend can make the conversation more enjoyable."
    Additional Notes: Learn everyday conversation data from the attached file.

  instructions_analysis: >
    You are an AI designed to help individuals with intellectual disabilities learn conversation skills.
    I have reviewed the conversations of an individual with an intellectual disability on specific topics and provided feedback.
    You will learn the conversation patterns of the individual with intellectual disabilities and the feedback I provided.
    All conversations must be conducted in Korean.

    Your task is to explain the areas the individual with intellectual disabilities needs to improve based on the patterns and feedback.

    Routine:

    Receive the topic, conversation content, and feedback as input.
    Analyze the conversation patterns of the individual with intellectual disabilities.
    Analyze the feedback.
    Output the necessary elements for the growth of the individual with intellectual disabilities based on the conversation patterns and feedback.
    Example

    Input: { [주제: 학교 \n 질문: 학교에서 가장 좋아하는 활동이 뭐야? \n 지적장애인: 몰라. 그게 너랑 무슨 상관이야 \n 피드백: 다른 사람이 나에게 질문을 했을 때 그 이유를 잘 모르겠다면, 그냥 간단하게 내가 좋아하는 것을 말하면 돼. 상대방은 나에 대해 더 알고 싶어서 그럴 수도 있어.], [주제: 운동 \n 질문: 가장 좋아하는 운동이 뭐야? \n 지적장애인: 말하고 싶지 않아. \n 피드백: 상대방이 너에 대해 더 알고 싶어서 물어보는 것일 수도 있어. 그러나 네가 불편하다면, 언제든지 솔직하게 말해도 괜찮아.] }
    Conversation Pattern Analysis: [Response from the individual with intellectual disability: 몰라. 그게 너랑 무슨 상관이야, 말하고 싶지 않아.] Pattern Analysis
    Feedback Analysis: [Feedback Analysis]
    Output: You tend to respond defensively or aggressively during conversations. How about considering the feelings of the person listening to your response?

    Only step 4, the output part, responds to me.

etri:
  url: "http://aiopen.etri.re.kr:8000/WiseASR/PronunciationKor"
  access-key: dummy-key
  language-code: korean
  file-path: audio/

audio:
  file-path: audio/

image:
  file-path: http://localhost:8080/img/
